#!/data/data/com.termux/files/usr/bin/bash
echo "=========================================="
echo "         PhoneVPS Live Status Check       "
echo "=========================================="
echo -n "MariaDB (MySQL)   : "
pgrep -f "mariadbd" >/dev/null && echo "[RUNNING]" || echo "[STOPPED]"
echo -n "PHP DB Manager    : "
pgrep -f "php -S" >/dev/null && echo "[RUNNING]" || echo "[STOPPED]"
echo -n "Node.js Engine    : "
pgrep -f "node server.js" >/dev/null && echo "[RUNNING]" || echo "[STOPPED]"
echo -n "Nginx Proxy       : "
pgrep -f "nginx" >/dev/null && echo "[RUNNING]" || echo "[STOPPED]"
echo -n "Cloudflare Tunnel : "
pgrep -f "cloudflared" >/dev/null && echo "[RUNNING]" || echo "[STOPPED]"
echo "------------------------------------------"
echo "Custom Domain     : https://vps.shokherpolli.com"
echo "phpMyAdmin URL    : https://vps.shokherpolli.com/phpmyadmin"
echo "File Manager URL  : https://vps.shokherpolli.com/files"
echo "=========================================="
